- gradle/testVerbose.gradle
- security-jwt/build.gradle
- security-ldap/build.gradle
- security-oauth2/build.gradle
- security-session/build.gradle
- security/build.gradle
This gets more verbosity when executing tests: 
```
... requires authentication PASSED
... without authentication PASSED
...  authenticated user PASSED
... one of those roles PASSED
... logged in user PASSED
...  logged in user PASSED
...-----------> 16% EXECUTING [25s]
------------------------------------------------------------------------
|  Results: SUCCESS (167 tests, 167 successes, 0 failures, 0 skipped)  |
------------------------------------------------------------------------
```
> test verbose logging

- security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/authorization/response/AuthorizationError.java
Simple fix of redirect URI mismatch error:
```
java.lang.IllegalArgumentException: No enum constant io.micronaut.security.oauth2.endpoint.authorization.response.AuthorizationError.REDIRECT_URI_MISMATCH
at java.base/java.lang.Enum.valueOf(Enum.java:240)
at io.micronaut.security.oauth2.endpoint.authorization.response.AuthorizationError.valueOf(AuthorizationError.java:25)
at io.micronaut.security.oauth2.endpoint.authorization.response.DefaultAuthorizationErrorResponse.getError(DefaultAuthorizationErrorResponse.java:61)
[...]
> Add missing REDIRECT_URI_MISMATCH enum element

- security/src/main/java/io/micronaut/security/handlers/RejectionHandler.java
"User" can be a machine, woman, man, multiple entities etc. This PR removes verbiage I came across while reading the docs that specifies the user as a man.
I hope the maintainers of this project understand implicit bias and appreciate PRs like this in the hopes of making the Micronaut community inclusive of all kinds of Engineers.
> Update Javadoc to make "user" not male-specific.

- security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/authorization/response/AuthorizationError.java
- security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/TokenError.java
- security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/TokenErrorResponse.java
- security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/token/response/TokenErrorSpec.groovy
This pull request fixes deserialization of enums in error messages and improves the message for errors when retrieving a token.
In my case there was a misconfigured client secret. There was not meaningful error in the logs, only debug messages of failed deserialization (see below). After I fixed the enum deserialization issue I also had to fix the message, because there was no information about the actual error in the logs.
```
17:52:08.657 [nioEventLoopGroup-1-29] DEBUG i.m.http.client.DefaultHttpClient - Sending HTTP Request: POST /auth/realms/master/protocol/openid-connect/token
17:52:08.657 [nioEventLoopGroup-1-29] DEBUG i.m.http.client.DefaultHttpClient - Chosen Server: localhost(8080)
17:52:08.667 [nioEventLoopGroup-1-29] DEBUG i.m.http.client.DefaultHttpClient - Unable to decode …
```
> Fix TokenError deserialization issue

- security/src/main/java/io/micronaut/security/utils/DefaultSecurityService.java
Check and type castto Collection instead of List when checking roles.
This should avoid erros since the constructor of UserDetails accepts a
Collection as well
> Typecast to Collection instead of List

- src/main/docs/guide/authenticationStrategies/jwt/jwtGenerator/jwtGeneratorSignature.adoc
overriding SecretSignatureConfiguration has no effect. overriding SecretSignature has the desired effect. One might want to look into the others as well, I have not verified their behavior myself.
> Change to the appropriate class to override

- security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/JwtTokenValidatorUtils.java
As per comments on issue #90, the specification states that the `alg` key of the jwk-set is optional and we can therefore not use it to check if the key-set supports the relevant algorithm. Specifically this breaks azure openid connect authentication as the azure key-set does not use `alg` and jwt validation therefore always fails with azure active directory. 
Just removing the check seems to do the trick. The `config.verify` call which is still there in the for loop will compare against the `kid` and do the appropriate validations. 
This change seems good to me and fixes the issue with azure openid auth, but I would be the first to admit that I'm not expert-level with jwt, jwk, openid, oauth etc so please feel free to change or reject if there are implications here that I missed. …
> Fixes issue #90 with jwt validation - removing check for supported alg:s

- security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/authorization/state/JacksonStateSerDes.java
- security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/authorization/request/OauthAuthorizationRedirectSpec.groovy
- security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/authorization/request/OpenIdAuthorizationRedirectSpec.groovy
This provides a solution for oidc proviers which return invalid state responses. e.g. `sign in with apple`
`/oauth/callback/apple?code=XXXXXXXXXXXX&state="{&quot;nonce&quot;:&quot;ea8eec4d-e2e5-4a72-9fd8-fc347d26f0e4&quot;}"`
> Base 64 state

- security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/authorization/state/DefaultState.java
It must be set for GraalVM native-image to work properly, see #176
> Added @Introspected annotation for DefaultState

- security/src/main/java/io/micronaut/security/rules/AbstractSecurityRule.java
For now, no public constructor is defined on `AbstractSecurityRule`, all is package private.
So we need to create all AbstractSecurityRule in package `io.micronaut.security.rules`
Just make `AbstractSecurityRule(RolesFinder rolesFinder)` public must be sufficient to be declared in own package
> Allow to override AbstractSecurityRule

- security-jwt/src/main/java/io/micronaut/security/token/jwt/generator/AccessRefreshTokenGenerator.java
- security-jwt/src/main/java/io/micronaut/security/token/jwt/generator/RefreshTokenConfiguration.java
- security-jwt/src/main/java/io/micronaut/security/token/jwt/generator/RefreshTokenConfigurationProperties.java
- security-jwt/src/main/java/io/micronaut/security/token/jwt/generator/SignedRefreshTokenGenerator.java
- security-jwt/src/test/groovy/io/micronaut/security/token/jwt/SecurityJwtBeansWithSecurityDisabledSpec.groovy
- security-jwt/src/test/groovy/io/micronaut/security/token/jwt/SecurityJwtBeansWithSecurityJwtDisabledSpec.groovy
- security-jwt/src/test/groovy/io/micronaut/security/token/jwt/endpoints/OauthControllerPathConfigurableSpec.groovy
- security-jwt/src/test/groovy/io/micronaut/security/token/jwt/endpoints/OauthControllerSpec.groovy
- security-jwt/src/test/groovy/io/micronaut/security/token/jwt/generator/RefreshTokenConfigurationEnabledSpec.groovy
- security-jwt/src/test/groovy/io/micronaut/security/token/jwt/generator/RefreshTokenConfigurationSpec.groovy
- security-jwt/src/test/groovy/io/micronaut/security/token/jwt/generator/RefreshTokenConfigurationToggeableSpec.groovy
- security-jwt/src/test/groovy/io/micronaut/security/token/jwt/generator/SignedRefreshTokenGeneratorSpec.groovy
- security-jwt/src/test/groovy/io/micronaut/testutils/ApplicationContextSpecification.groovy
- src/main/docs/guide/authenticationStrategies/jwt/jwtGenerator.adoc
- src/main/docs/guide/endpoints/refresh.adoc
This is an attempt to simplify `refresh token` generation. 
This is our current implementation
https://github.com/micronaut-projects/micronaut-security/blob/5eab9f801fb43a11c7575078b83be7c648c84ac7/security-jwt/src/main/java/io/micronaut/security/token/jwt/generator/SignedRefreshTokenGenerator.java
and this is my proposed solution: 
https://github.com/micronaut-projects/micronaut-security/blob/simpler-refresh-token-generator/security-jwt/src/main/java/io/micronaut/security/token/jwt/generator/JwsRefreshTokenGenerator.java
It leverages [Nimbus JOSE](https://connect2id.com/products/nimbus-jose-jwt/examples/jws-with-hmac), which is already in the classpath, to sign a payload. 
Moreover, it has more configuration options. For example, it enables you to configure a different JWS Algorithm than …
> refactor: simpler refresh token generator

- security/src/main/java/io/micronaut/security/token/reader/HttpHeaderTokenReader.java
- security/src/test/groovy/io/micronaut/security/token/reader/HttpHeaderTokenReaderSpec.groovy
> [WIP] Make Authorization header prefix check case insensitive

- security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/validation/DefaultOpenIdTokenResponseValidator.java
- security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/validation/NonceClaimValidator.java
- security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/token/response/validation/NonceClaimValidatorDisableSpec.groovy
- security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/token/response/validation/NonceClaimValidatorSpec.groovy
Other claims validator such as [`ExpirationJwtClaimsValidator.java`](https://github.com/micronaut-projects/micronaut-security/blob/master/security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/ExpirationJwtClaimsValidator.java) or  [`SubjectNotNullJwtClaimsValidator`](https://github.com/micronaut-projects/micronaut-security/blob/master/security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/SubjectNotNullJwtClaimsValidator.java) can be disabled via configuration. I think we should do the same for the nonce validator.
> feat: allow NonceClaimValidator to be disabled

- security-jwt/src/main/java/io/micronaut/security/token/jwt/endpoints/KeysController.java
- security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/ExpirationJwtClaimsValidator.java
- security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/JwtClaimsValidator.java
- security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/JwtTokenValidator.java
- security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/JwtValidator.java
- security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/SubjectNotNullJwtClaimsValidator.java
- security-jwt/src/test/groovy/io/micronaut/docs/jwtclaimsoverride/JwtClaimsOverrideSpec.groovy
- security-jwt/src/test/groovy/io/micronaut/security/token/jwt/validator/JwtClaimsValidatorRequestNotPassedByDefaultSpec.groovy
- security-jwt/src/test/groovy/io/micronaut/security/token/jwt/validator/JwtClaimsValidatorRequestPassedSpec.groovy
- security/src/main/java/io/micronaut/security/token/TokenAuthenticationFetcher.java
- security/src/main/java/io/micronaut/security/token/validator/TokenValidator.java
Close: https://github.com/micronaut-projects/micronaut-security/issues/381
> refactor: add request to jwt claims validator

- security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/authorization/response/DefaultOpenIdAuthorizationResponseHandler.java
The goal is that you can override easily the request being made to the token endpoint. If you are working with an authorization server non standard. 
e.g. You could just override the `sendRequest` method. 
```java
protected Publisher<OpenIdTokenResponse> sendRequest(OpenIdAuthorizationResponse authorizationResponse,
OauthClientConfiguration clientConfiguration,
SecureEndpoint tokenEndpoint) {
return httpClient.retrieve(createRequest(authorizationResponse, clientConfiguration), OpenIdTokenResponse.class);
}
private HttpRequest<?> createRequest(OpenIdAuthorizationResponse authorizationResponse,
OauthClientConfiguration clientConfiguration) {
return HttpRequest.POST("/api/v1/openid/token", new HashMap<String, String>() {{
put("code", authorizationResponse.getCode());
put("client_id", …
```
> refactor: split DefaultOpenIdAuthorization methods

- gradle.properties
Disable Kotlin stdlib as api dependency closes #414 using **gradle.properties**
`kotlin.stdlib.default.dependency=false`
> Opt-out kotlin stdlib api dependency closes #414

- security-jwt/src/main/java/io/micronaut/security/token/jwt/generator/DefaultAccessRefreshTokenGenerator.java
I think it is not valid, because `refreshToken` parameter can be `null` if `RefreshTokenValidator` and `RefreshTokenPersistence` beans are not provided.
Now it is hard to extend and override those methods, because in Kotlin it results in non-nullable type and invalid checking agains `null` value.
> Remove NonNull annotation of refreshToken parameter

- security-oauth2/src/main/java/io/micronaut/security/oauth2/client/DefaultOauthClient.java
- security-oauth2/src/main/java/io/micronaut/security/oauth2/configuration/OauthClientConfiguration.java
I want to move this to the interface. I want to use this logic outside of `DefaultOauthClient`. .e.g at client crendentials grant.
> refactor: move getTokenEndpoint to interface

- security-oauth2/src/test/groovy/io/micronaut/security/oauth2/Keycloak.groovy
- security-oauth2/src/test/groovy/io/micronaut/security/oauth2/e2e/AuthenticationModeIdTokenSpec.groovy
- security-oauth2/src/test/groovy/io/micronaut/security/oauth2/e2e/OpenIdAuthorizationCodeSpec.groovy
- security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/authorization/request/OpenIdAuthorizationRedirectOauthDisabledSpec.groovy
- security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/authorization/request/OpenIdAuthorizationRedirectSpec.groovy
- security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/authorization/request/OpenIdAuthorizationRedirectWithJustOpenIdSpec.groovy
To ignore the tests which require tescontainers pass system property `testcontainers`
```
./gradlew -Dtestcontainers=false test
```
> test: Keycloak can be ignored sys testcontainers

- security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/TokenResponse.java
- security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/token/response/TokenResponseSpec.groovy
I want to use equals for `TokenResponse` in a separate PR.
> feat: add equals and hashcode to TokenResponse

- security-oauth2/src/main/java/io/micronaut/security/oauth2/client/clientcredentials/AbstractClientCredentialsClient.java
- security-oauth2/src/main/java/io/micronaut/security/oauth2/client/clientcredentials/CacheableProcessor.java
- security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/TokenResponse.java
- security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/TokenResponseExpiration.java
- security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/token/response/TokenResponseSpec.groovy
This moves the logic of calculating an expiration date for a token directly into the `TokenResponse` POJO. So that it is easier to get rid of `CacheableProcessor`.
> refactor: add expiration to TokenResponse

- src/main/docs/guide/oauth/flows/clientcredentials/clientecredentialshttpclient.adoc
Fix typos in client credentials docs and config example
> doc: fix copy in client-credentials section

- security-oauth2/src/main/java/io/micronaut/security/oauth2/client/IdTokenClaimsValidator.java
I have refactored `IdTokenClaimsValidator` so that it is easy to create replacement and reuse logic. While reviewing https://github.com/micronaut-projects/micronaut-openapi/pull/448 I had to create such a replacement: 
```java
@Singleton
@Replaces(IdTokenClaimsValidator.class)
public class IdTokenClaimsValidatorReplacement extends IdTokenClaimsValidator {
public static final String CLIENT_ID = "client_id";
public IdTokenClaimsValidatorReplacement(Collection<OauthClientConfiguration> oauthClientConfigurations) {
super(oauthClientConfigurations);
}
@Override
public boolean validate(JwtClaims claims) {
Optional<String> claimIssuerOptional = parseIssuerClaim(claims);
if (!claimIssuerOptional.isPresent()) {
return false;
}
String iss = claimIssuerOptional.get();
Optional<List<String>> …
```
> refactor: IdTokenClaimsValidator

- security-oauth2/src/main/java/io/micronaut/security/oauth2/configuration/OauthClientConfigurationProperties.java
I have done this change to expose the default scopes in [Micronaut security Configuration Reference](https://micronaut-projects.github.io/micronaut-security/latest/guide/configurationreference.html)
> javadoc: default scopes in configuration reference

- build.gradle
[Project template](https://github.com/micronaut-projects/micronaut-project-template) no longer contains a repositories block for root `build.gradle`
> remove unuecessary repository block

- build.gradle
[Project Template](https://github.com/micronaut-projects/micronaut-project-template) does not contain this snippet. I think it is done here: 
https://github.com/micronaut-projects/micronaut-build/blob/630b097c64e4634998de9b842bb96487cb637cce/src/main/groovy/io/micronaut/build/MicronautDependencyUpdatesPlugin.groovy#L44-L47
> build: remove unnecessary selection reject

- security/src/main/java/io/micronaut/security/rules/SensitiveEndpointRule.java
- src/main/docs/guide/securityRule/builtInEndpointsAccess.adoc
- test-suite-groovy/src/test/groovy/io/micronaut/security/oauth2/docs/managementendpoints/LoggerSpec.groovy
- test-suite-groovy/src/test/groovy/io/micronaut/security/oauth2/docs/managementendpoints/SensitiveEndpointRuleReplacement.groovy
- test-suite-kotlin/build.gradle
- test-suite-kotlin/src/test/groovy/io/micronaut/security/oauth2/docs/ConfigurationFixture.groovy
- test-suite-kotlin/src/test/groovy/io/micronaut/security/oauth2/docs/EmbeddedServerSpecification.groovy
- test-suite-kotlin/src/test/groovy/io/micronaut/security/oauth2/docs/managementendpoints/LoggersSpec.groovy
- test-suite-kotlin/src/test/kotlin/io/micronaut/security/oauth2/docs/managementendpoints/SensitiveEndpointRuleReplacement.kt
- test-suite/src/test/groovy/io/micronaut/security/oauth2/docs/ConfigurationFixture.groovy
- test-suite/src/test/groovy/io/micronaut/security/oauth2/docs/EmbeddedServerSpecification.groovy
- test-suite/src/test/groovy/io/micronaut/security/oauth2/docs/managementendpoints/LoggersSpec.groovy
- test-suite/src/test/java/io/micronaut/security/oauth2/docs/managementendpoints/SensitiveEndpointRuleReplacement.java
close: https://github.com/micronaut-projects/micronaut-security/issues/606
close: https://github.com/micronaut-projects/micronaut-security/pull/589
@oscarcitoz this PR refactors `SensitiveEndpointRule` to ease replacement. Moreover, it documents how to restrict management endpoints for a particular role.
> docs: improve documentation about SensitiveEndpointRule replacement

- security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/request/DefaultTokenEndpointClient.java
Fix: https://github.com/micronaut-projects/micronaut-security/issues/623
I have published to maven local and verified it solves #623
> fix: use a Memoized supplier for DefaultTokenClient

- security-jwt/src/main/java/io/micronaut/security/token/jwt/cookie/CookieLoginHandler.java
- security-jwt/src/main/java/io/micronaut/security/token/jwt/cookie/JwtCookieLoginHandler.java
- security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/IdTokenLoginHandler.java
I'm using this module with GraphQL login implementation where I need to call some classes directly, and instead of copy-paste the whole method to generate cookies from `UserDetails` object it will be better to open access to these methods. This will help to reuse these methods after upgrade to the new version.
This is an example of how I use this code in GraphQL endpoints: https://github.com/expatiat/dumper/blob/main/dumper-api/src/main/java/com/zhokhov/dumper/api/graphql/mutation/UserLoginServerMutation.java
This method is mostly copy-pasted from `JwtCookieLoginHandler` class:
`private Optional<Cookie> accessTokenCookie(UserDetails userDetails, HttpRequest<?> request)`
> Make public access to getCookies methods in CookieLoginHandler class.

- security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/DefaultOpenIdUserDetailsMapper.java
- security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/OpenIdUserDetailsMapper.java
- test-suite-groovy/src/test/groovy/io/micronaut/security/oauth2/docs/openid/GlobalOpenIdUserDetailsMapper.groovy
- test-suite-kotlin/src/test/kotlin/io/micronaut/security/oauth2/docs/openid/GlobalOpenIdUserDetailsMapper.kt
- test-suite-kotlin/src/test/kotlin/io/micronaut/security/oauth2/docs/openid/OktaUserDetailsMapper.kt
- test-suite/src/test/java/io/micronaut/security/oauth2/docs/openid/GlobalOpenIdUserDetailsMapper.java
- test-suite/src/test/java/io/micronaut/security/oauth2/docs/openid/OktaUserDetailsMapper.java
delete deprecated method OpenIdUserDetailsMapper:createAuthenticationResponse(String, OpenIdTokenResponse, OpenIdClaims)
> BREAKING CHANGE: del createAuthenticationResponse

- security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/JwtValidator.java
Add logging when validating encrypted or signed JWTs and there is no config.
> Log on missing JWT configs in validation

- security-jwt/src/test/groovy/io/micronaut/security/token/jwt/cookie/LoginForm.groovy
>  io.micronaut.core.beans.exceptions.IntrospectionException: No bean introspection available for type [class io.micronaut.security.token.jwt.cookie.LoginForm]. Ensure the class is annotated with io.micronaut.core.annotation.Introspected
> test: annotate LoginForm with @Introspected

- security/src/main/java/io/micronaut/security/token/refresh/RefreshTokenPersistence.java
- src/main/docs/guide/breaks.adoc
To keep the API as in 2.5.x https://github.com/micronaut-projects/micronaut-security/blob/2.5.x/security/src/main/java/io/micronaut/security/token/refresh/RefreshTokenPersistence.java
> reverts changes to RefreshTokenPersistence

- security-jwt/src/main/java/io/micronaut/security/token/jwt/cookie/JwtCookieClearerLogoutHandler.java
- security-jwt/src/test/groovy/io/micronaut/security/token/jwt/cookie/JwtCookieClearerLogoutHandlerSpec.groovy
Fixes #718 by clearing the Token and Refresh Token Cookies anyway.
> Fix: JWT Refresh Token Cookie not getting cleared (#718)

- security/src/main/java/io/micronaut/security/errors/CookiePriorToLoginPersistence.java
Please feel free to correct me if my approach is wrong to any of this. 
From my testing, I've found that Chrome will refuse to include cookies in requests where their path does not match the browser URI path exactly or is a superdirectory of the browser path. Most auth providers will redirect back to a path or subfolder that does not match the path of the ORIGINAL_URI.
For example:
Cookie ORIGINAL_URI: `/abc/123`
Config callback-uri: `/google/etc/`
The path for ORIGINAL_URI will be `/abc` which Chrome will not send to `/google`. Debugging the application I've found that it is not finding a cookie config so it is defaulting to null which seems to have the effect of defaulting to path of the URI where the cookie is set.
By defaulting the path to root, this should avoid this in most use …
> For PriorToLogin if there is no cookie configuration, default the path to root

- security-oauth2/src/main/java/io/micronaut/security/oauth2/client/clientcredentials/ClientCredentialsConfiguration.java
- security-oauth2/src/main/java/io/micronaut/security/oauth2/configuration/OauthClientConfigurationProperties.java
- security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/request/context/ClientCredentialsTokenRequestContext.java
- security-oauth2/src/test/groovy/io/micronaut/security/oauth2/client/clientcredentials/ClientCredentialsConfigurationSpec.groovy
- Added `getAdditionalRequestParams` into the `ClientCredentialsConfiguration` interface
- Added `additionalRequestParams` to the `ClientCredentialsConfigurationProperties`, including getter and setter.
- Added `additionalRequestParams` to `ClientCredentialsTokenRequestContext` 
- In `ClientCredentialsTokenRequestContext`, inject extra parameters when the `ClientCredentialsGrant` is converted to a map
- Added a test to verify that the binding of the added configuration properties are valid
Todo(?)
closes #751
> Inject "additional-request-params" into the SecureGrantMap produced by  ClientCredentialsTokenRequestContext::getGrant

- security-annotations/src/main/java/io/micronaut/security/annotation/DenyAllAnnotationMapper.java
- security-annotations/src/main/java/io/micronaut/security/annotation/JakartaDenyAllAnnotationMapper.java
- security-annotations/src/main/java/io/micronaut/security/annotation/JakartaPermitAllAnnotationMapper.java
- security-annotations/src/main/java/io/micronaut/security/annotation/JakartaRolesAllowedAnnotationMapper.java
- security-annotations/src/main/java/io/micronaut/security/annotation/PermitAllAnnotationMapper.java
- security-annotations/src/main/java/io/micronaut/security/annotation/RolesAllowedAnnotationMapper.java
- security-annotations/src/main/resources/META-INF/services/io.micronaut.inject.annotation.AnnotationMapper
- security/src/test/groovy/io/micronaut/security/denyall/JakartaDenyAllSpec.groovy
- security/src/test/groovy/io/micronaut/security/permitall/JakartaPermitAllSpec.groovy
- security/src/test/groovy/io/micronaut/security/rolesallowed/JakartaRolesAllowedSpec.groovy
- src/main/docs/guide/securityRule/secured.adoc
Switched over the AnnotationMappers for javax security annotations to NamedAnnotationMapper as discussed in #774.
Added the Jakarta equaivalent mappers by extending the javax ones and overriding the namespace.
closes #774
> Add jakarta security annotation mapping

- settings.gradle
Replaces the old configuration with the standard Micronaut publication
to ge.micronaut.io
> Enable build scans

- security/src/main/java/io/micronaut/security/filters/SecurityFilter.java
- security/src/main/java/io/micronaut/security/filters/SecurityFilterConfiguration.java
- security/src/main/java/io/micronaut/security/filters/SecurityFilterConfigurationProperties.java
- security/src/test/groovy/io/micronaut/security/filters/SecurityFilterDisabledSpec.groovy
- security/src/test/groovy/io/micronaut/security/filters/SecurityFilterPatternSpec.groovy
This is useful for people who want to use Micronaut security features (token validation, client credentials) but they don't need route validation. 
Closes #550
> feat: SecurityFilter toggeable and configurable pattern

- security/src/main/java/io/micronaut/security/authentication/AbstractPrincipalArgumentBinder.java
- security/src/main/java/io/micronaut/security/authentication/AuthenticationArgumentBinder.java
- security/src/main/java/io/micronaut/security/authentication/PrincipalArgumentBinder.java
@burtbeckwith  I've extracted this improvement into its own PR and use it also for `PrincipalArgumentBinder`
> refactor: extract AbstractPrincipalArgumentBinder

- security/src/main/resources/META-INF/native-image/io.micronaut.security/micronaut-security/native-image.properties
This PR fixes the following GraalVM warning:
```
Warning: class initialization of class io.micronaut.security.rules.$SensitiveEndpointRule$Definition failed with exception java.lang.NoClassDefFoundError: io/micronaut/management/endpoint/EndpointSensitivityProcessor. This class will be initialized at run time because option --allow-incomplete-classpath is used for image building. Use the option --initialize-at-run-time=io.micronaut.security.rules.$SensitiveEndpointRule$Definition to explicitly request delayed initialization of this class.
```
> Fix GraalVM warning

- security/src/main/java/io/micronaut/security/rules/SecurityRule.java
I believe now Micronaut supports many authentication methods and not only JWT.
So SecurityRule must mention SecurityFilter instead.
> javadoc: SecurityFilter should mention SecurityFilter instead of JWT

- security/src/main/java/io/micronaut/security/authentication/BasicAuthUtils.java
- security/src/test/groovy/io/micronaut/security/authentication/BasicAuthUtilsSpec.groovy
relate to https://github.com/tchiotludo/akhq/issues/939
see https://dev.to/ethanarrowood/what-characters-should-be-allowed-in-http-basic-authentication-userid-and-password-48f0
> Based on this RFC2617 Specification, HTTP Basic Authentication userid can contain any TEXT excluding the symbol :. The password can contain any TEXT. Are these the only rules for Basic Authentication usernames and passwords?
> fix: basic auth must allow password with :

- security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/validation/AudienceClaimValidator.java
- security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/token/response/validation/IdTokenValidatorSpec.groovy
See: https://github.com/micronaut-projects/micronaut-security/pull/899
> fix: id token validation fails if aud contains multiple values, aud does not contain client_id and azp claim is present

- security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/validation/AudienceClaimValidator.java
- security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/token/response/validation/AudienceClaimValidatorSpec.groovy
Current version of the validator returns `true` when:
- audience claim contains multiple values, and 
- `azp` claim is present
regardless whether `client_id` is present in audience or not.
This PR suggest a test covering this case and also fix for it.
> Audience client_id validation

- test-suite-utils/src/main/resources/GebConfig.groovy
The x86 container fails to start or run quick enough for the tests
to pass on an m1 mac
This replaces
selenium/standalone-firefox
with
seleniarm/standalone-firefox
Which is an ARM based fork of the selenium docker project
https://hub.docker.com/u/seleniarm
https://github.com/seleniarm/docker-selenium
> test: use ARM builds of selenium container on M1 macs

- security-oauth2/src/test/groovy/io/micronaut/security/oauth2/e2e/LoginPage.groovy
- test-suite-utils/src/main/groovy/io/micronaut/security/testutils/Keycloak.groovy
- test-suite-utils/src/main/resources/Dockerfile.keycloak
On an Apple M1 computer, the x86 Keycloak image runs too slowly and the tests fail.
This change updates Keycloak to the latest version, and builds an ARM version when run
on M1 hardware so the tests pass when run locally.
> test: Keycloak to v16 and fix tests for M1 apple hardware

- src/main/docs/guide/securityConfiguration/noRedirection.adoc
It appears that `micronaut.security.redirection.enabled` should be `micronaut.security.redirect.enabled`.
> Correct configuration setting name

- security/src/main/java/io/micronaut/security/authentication/ClientAuthentication.java
- security/src/test/groovy/io/micronaut/security/authentication/AuthenticationSerializationSpec.groovy
Handle missing attributes for ClientAuthentication deserialization the same way as the ServerAuthentication constructor, i.e. by using an empty attribute map.
Fixes #1038
> Fix deserialization of Authentication without attributes

- security-oauth2/build.gradle
The `oauth2` module depends on a test suite, which is wrong.
> Fix dependency scope

- security/src/main/java/io/micronaut/security/authentication/AuthenticationModeCondition.java
- test-suite-graal/build.gradle
Custom conditions are encoding into the AnnotationMetadata which is initialized at build time, for this reason conditions can never use logging safely otherwise they will initialize the log infrastructure. This PR moves  the logging in `AuthenticationModeCondition` to a static inner class which avoids initializing the logging when the class is initialized.
> Avoid initializing logging at build time for GraalVM

- security-aot/src/main/java/io/micronaut/security/aot/OpenIdProviderMetadataFetcherCodeGenerator.java
- security-aot/src/test/groovy/io/micronaut/security/aot/OpenIdProviderMetadataFetcherCodeGeneratorSpec.groovy
- security-oauth2/src/main/java/io/micronaut/security/oauth2/client/DefaultOpenIdProviderMetadata.java
- security-oauth2/src/test/groovy/io/micronaut/security/oauth2/client/DefaultOpenIdProviderMetadataSpec.groovy
This PR adds a builder for `DefaultOpenIdProviderMetadata` and uses the builder in the AOT code generation.
In Micronaut Security 4.0, I want to remove the setters from DefaultOpenIdProviderMetadata, and the builder is helpful in avoiding calling a constructor with too many parameters from the AOT code.
> feat: builder of DefaultOpenIdProviderMetadata

- security/src/test/groovy/io/micronaut/docs/security/authorization/X509AuthorizationSpec.groovy
- security/src/test/groovy/io/micronaut/security/x509/AbstractX509Spec.groovy
Replace deprecated micronaut.ssl.build-self-signed and use micronaut.server.ssl.build-self-signed instead.
Replace deprecated micronaut.ssl.port with micronaut.server.ssl.port
Contributed by @altro3 via: https://github.com/micronaut-projects/micronaut-security/pull/1260
> test: move deprecated config to micronaut.server.ssl

- security/src/main/java/io/micronaut/security/filters/SecurityFilter.java
Avoid `NullPointerException` when degub is enabled
> fix 1278-security-filter-nullpointer-debug

- security-jwt/src/test/groovy/io/micronaut/security/token/jwt/cookie/JwtCookieAuthenticationNoRedirectSpec.groovy
- security/src/main/java/io/micronaut/security/token/cookie/CookieLoginHandler.java
- src/main/docs/guide/breaks.adoc
For applications with `micronaut.security.authentication` set to `cookie` and `micronaut.security.redirect.enabled` set to `false`, the server responds with 401 HTTP Status code instead of 200 for login failed attempts.
see https://github.com/micronaut-projects/micronaut-security/issues/1222
> BREAKS: change Status for no redirect and  cookie

- src/main/docs/guide/oauth/flows/authorization-code/openid-authorization-code/openid-user-details.adoc
This PR documents that it is not possible to use `micronaut.security.authentication` = `idtoken` with a custom `OpenIdAuthenticationMapper`. When you use a custom `OpenIdAuthenticationMapper` is because you wish to modify the originall idtoken and add for example extra claims. That requries generate a new token. When you use `idtoken`, you say that you want to use the OAutheServer `idtoken` directly
Close #1391
> doc: idtoken not custom OpenIdAuthenticationMapper

- security/src/main/java/io/micronaut/security/endpoints/LoginController.java
- security/src/main/java/io/micronaut/security/event/LoginFailedEvent.java
- security/src/test/groovy/io/micronaut/security/events/EventListenerSpec.groovy
> feat: add AuthenticationRequest to LoginFailedEvent

- security-jwt/src/main/java/io/micronaut/security/token/jwt/endpoints/TokenRefreshRequest.java
- test-suite-serde/src/test/groovy/io/micronaut/security/token/jwt/endpoints/SerdeSpec.groovy
Fixes previous PR #1432
Seems the constructor previously created receiving only the `refreshToken` and defaulting `grantType` to `refresh_token` was a shorthand to be used on tests.
To avoid breaking binary compatibility changing a public constructor of a non-private class `TokenRefreshRequest` I have created another constructor receiving both parameters and marked it instead with @Creator.
That just bump in with tests in `OauthControllerSpec`. Sorry about that.
> Move @Creator to a new appropriate constructor

- security/src/main/java/io/micronaut/security/token/generator/TokenGenerator.java
Fix incorrect time unit in Javadoc. The comment on "expiration" was indicating the value is in "milliseconds", but this value is in "seconds" in io.micronaut.security.token.jwt.generator.JwtTokenGenerator
> Alter Javadoc in TokenGenerator.java

- config/accepted-api-changes.json
- security-ldap/src/main/java/io/micronaut/security/ldap/LdapAuthenticationProvider.java
- security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/request/password/OauthPasswordAuthenticationProvider.java
- security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/request/password/OpenIdPasswordAuthenticationProvider.java
- security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/request/password/PasswordGrantFactory.java
- security/src/main/java/io/micronaut/security/authentication/AuthenticationProvider.java
- security/src/main/java/io/micronaut/security/authentication/Authenticator.java
- security/src/main/java/io/micronaut/security/authentication/BasicAuthAuthenticationFetcher.java
- security/src/main/java/io/micronaut/security/authentication/provider/ExecutorAuthenticationProvider.java
- security/src/main/java/io/micronaut/security/authentication/provider/ReactiveAuthenticationProviderAdapter.java
- security/src/main/java/io/micronaut/security/endpoints/LoginController.java
- security/src/test/groovy/io/micronaut/security/authentication/AuthenticatorSpec.groovy
- security/src/test/groovy/io/micronaut/security/authentication/DeprecatedAuthenticationProviderStillWorksSpec.groovy
Several breaking changes were introduced accidentally in https://github.com/micronaut-projects/micronaut-security/pull/1526
if a user had a bean extending `AuthenticationProvider` they will get: 
```
java/example/micronaut/AuthenticationProviderUserPassword.java:29: error: wrong number of type arguments; required 3
public class AuthenticationProviderUserPassword implements AuthenticationProvider<HttpRequest<?>>  { // <2>
^
````
This PR reverts the changes to `Authenticator` and `AuthenticationProvider` so that users are able to upgrade their applications and see only a deprecation notice.
> revert breaking change

- security/src/main/java/io/micronaut/security/authentication/UsernamePasswordCredentials.java
- settings.gradle
- test-suite-jackson-databind-bean-introspection-module-false/build.gradle.kts
- test-suite-jackson-databind-bean-introspection-module-false/src/test/java/io/micronaut/security/jacksondatabind/beanintrospectionfalse/UsernamePasswordCredentialsBeanIntrospectionModuleFalseTest.java
- test-suite-jackson-databind-bean-introspection-module-false/src/test/java/io/micronaut/security/jacksondatabind/beanintrospectionfalse/UsernamePasswordCredentialsTest.java
- test-suite-jackson-databind-bean-introspection-module-false/src/test/resources/logback.xml
Suppor serialization of UsernamePasswordCredentials for jackson.bean-introspection-module=false
> fix: U…Credentials bean-introspection-module=false

- security-jwt/src/test/groovy/io/micronaut/security/token/jwt/cookie/JwtCookieClearerLogoutHandlerSpec.groovy
- security/src/main/java/io/micronaut/security/token/cookie/TokenCookieClearerLogoutHandler.java
Hi!
I've noticed that in the `TokenCookieClearerLogoutHandler` class, the `logout()` method seems to ignore the configuration of the _SameSite_, _Secure_, and _HTTPOnly_ attributes, focusing only on _Domain_, _Path_, _Name_, and _Max-Age_.
I wonder if this behaviour could deny cross-site authentication proxies from revoking authentication cookies with SameSite=None, Secure, and HTTPOnly attributes, even if originally provided by the proxy itself.
For example, in Chrome v120 I've got exactly replicated this issue, while the logout it's still working in Firefox:
I'm not sure if there are specific reasons for the current implementation, but in case the mentioned attributes should also be handled during the logout phase, I propose the attached pull request.
To ensure consistency within the …
> SameSite cookie attribute handling on logout

- security/src/main/java/io/micronaut/security/token/validator/TokenValidator.java
As discussed in https://github.com/micronaut-projects/micronaut-security/issues/1602#issuecomment-1960062247
> Clarify non-blocking requirements in TokenValidator#validateToken javadoc

- security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/jwks/JwksSignature.java
- security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/JwtTokenValidator.java
- security-jwt/src/test/groovy/io/micronaut/docs/jwks/JwksSpec.groovy
- security-oauth2/build.gradle.kts
- security-oauth2/src/test/groovy/io/micronaut/security/oauth2/client/JwksUriSignatureTimeoutSpec.groovy
- src/main/docs/guide/authenticationStrategies/jwt/jwtValidation/jwks.adoc
`JwtTokenValidator` is modified to explicitly execute `JwtValidator.validate` in a separate thread from the Netty event loop.
`JwtValidator.validate` is blocking in its current implementation and this allows it to be executed in a non-blocking fashion.
This is a short-term fix for #1633, where the preferred long-term fix would be to refactor the `JwtValidator` API to be non-blocking.
NOTE: For this fix, I have chosen to simply use the standard Reactor Bounded Elastic scheduler for the separate thread execution, rather than requiring modification of the `JwtTokenValidator` constructor to inject an ExecutorService. Refactoring `JwtValidator` and `JwksSignature` to be fully non-blocking would remove the need for the explicit scheduler, thus my preference for not changing the constructor.
> Offload JWK Set fetching from the event loop
