security-oauth2/src/main/java/io/micronaut/security/oauth2/configuration/OauthConfiguration.java, security-oauth2/src/main/java/io/micronaut/security/oauth2/configuration/OauthConfigurationProperties.java, security-oauth2/src/main/java/io/micronaut/security/oauth2/routes/OauthRouteBuilder.java, security-oauth2/src/main/java/io/micronaut/security/oauth2/url/DefaultOauthRouteUrlBuilder.java
* Add configuration property
* Create default login and callback routes if a default provider is
configured
=> Add support a for default OAuth provider

security-oauth2/src/main/java/io/micronaut/security/oauth2/client/condition/OpenIdClientCondition.java, security-oauth2/src/test/groovy/io/micronaut/security/oauth2/client/condition/OpenIdClientConditionSpec.groovy
Close: https://github.com/micronaut-projects/micronaut-security/issues/53
=> Fix `OpenIdClientCondition` evaluates to false if `issuer` not present.

security-jwt/src/main/java/io/micronaut/security/token/jwt/generator/JwtTokenGenerator.java
It should be seconds instead of milliseconds
=> Update docs expiration time unit

security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/authorization/request/DefaultOauthAuthorizationRequest.java, security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/authorization/request/DefaultOpenIdAuthorizationRequest.java, security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/authorization/response/DefaultOauthAuthorizationResponseHandler.java, security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/authorization/state/DefaultState.java, security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/authorization/state/DefaultStateFactory.java, security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/authorization/state/State.java, security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/authorization/state/StateFactory.java, security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/request/context/OauthCodeTokenRequestContext.java, security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/authorization/request/OauthAuthorizationRedirectSpec.groovy, security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/authorization/request/OpenIdAuthorizationRedirectSpec.groovy
=> Including redirect_uri in the token request

src/main/docs/guide/securityEvents.adoc
Close: https://github.com/micronaut-projects/micronaut-security/issues/138
=> Fix link to Micronaut Context Events

security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/jwks/JwksSignature.java
Closes https://github.com/micronaut-projects/micronaut-security/issues/133
=> Include url in error message when JWKSet can't be loaded

gradle/license.gradle, security-jwt/src/main/resources/META-INF/native-image/io.micronaut.security/token-jwt/native-image.properties, security-ldap/src/main/java/io/micronaut/configuration/security/ldap/LdapAuthenticationProvider.java, security-ldap/src/main/java/io/micronaut/configuration/security/ldap/LdapAuthenticationProviderFactory.java, security-ldap/src/main/java/io/micronaut/configuration/security/ldap/package-info.java, security-ldap/src/test/groovy/io/micronaut/security/ldap/DisableLdapSpec.groovy, security-ldap/src/test/resources/logback.xml, security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/authorization/request/OauthAuthorizationRedirectSpec.groovy, src/main/docs/guide/ldap.adoc
=> Adding options to disable LDAP

security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/jwks/JwksSignature.java, security-jwt/src/test/groovy/io/micronaut/security/token/jwt/signature/jwks/JwksSignature500Spec.groovy, security-jwt/src/test/groovy/io/micronaut/security/token/jwt/signature/jwks/NotAvailableRemoteJwksSpec.groovy, security-oauth2/src/main/java/io/micronaut/security/oauth2/client/JwksUriSignatureFactory.java, security-oauth2/src/test/groovy/io/micronaut/security/oauth2/client/JwksUriSignatureSpec.groovy, security-oauth2/src/test/groovy/io/micronaut/security/oauth2/e2e/OpenIdAuthorizationCodeSpec.groovy
Close: https://github.com/micronaut-projects/micronaut-security/issues/155
Close: https://github.com/micronaut-projects/micronaut-security/issues/157
=> Fixes several Json Web Key Set scenarios

gradle.properties, security-jwt/src/main/java/io/micronaut/security/token/jwt/cookie/JwtCookieConfigurationProperties.java, security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/jwks/JwksSignature.java, security-jwt/src/test/groovy/io/micronaut/security/token/jwt/cookie/JwtCookieSameSiteSpec.groovy
PR for https://github.com/micronaut-projects/micronaut-security/issues/217
=> Add SameSite property to JwtConfigurationProperties

security/src/main/java/io/micronaut/security/utils/DefaultSecurityService.java, security/src/test/groovy/io/micronaut/security/authorization/SecuredRolesCaseSensitiveSpec.groovy
Closes: https://github.com/micronaut-projects/micronaut-security/issues/325
=> fix: SecurityService::hasRole case sensitive

security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/validation/DefaultOpenIdTokenResponseValidator.java
See: https://github.com/micronaut-projects/micronaut-security/issues/346
=> log: better logging if nonce validator fails

security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/JwtValidator.java
don't parse unless two dots
Close: https://github.com/micronaut-projects/micronaut-security/issues/344
=> refactor: move JWTValidator logging to trace level

security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/validation/DefaultOpenIdTokenResponseValidator.java
see: https://github.com/micronaut-projects/micronaut-security/issues/346
=> refactor: extract two proteced methods to simplify override

src/main/docs/guide/releaseHistory.adoc, src/main/docs/guide/toc.yml
Close: https://github.com/micronaut-projects/micronaut-security/issues/366
=> doc: Add release History section

src/main/docs/guide/breaks.adoc
Can be reverted when https://github.com/micronaut-projects/micronaut-security/pull/283 gets merged
=> Remove section about UserDetails being deleted

gradle.properties
See: https://github.com/micronaut-projects/micronaut-security/issues/422
=> bump up micronaut to 2.1.3

gradle.properties
close: https://github.com/micronaut-projects/micronaut-security/issues/422
=> ci: bump up micronaut to 2.1.3

src/main/docs/guide/authenticationStrategies/jwt/jwtEncryption.adoc, src/main/docs/guide/authenticationStrategies/jwt/jwtEncryption/jwtGeneratorEncryption.adoc, src/main/docs/guide/authenticationStrategies/jwt/jwtGenerator/jwtGeneratorRSA.adoc, src/main/docs/guide/authenticationStrategies/jwt/jwtGenerator/jwtGeneratorSecret.adoc, src/main/docs/guide/authenticationStrategies/jwt/jwtGenerator/jwtGeneratorSignature.adoc, src/main/docs/guide/authenticationStrategies/jwt/jwtValidation.adoc, src/main/docs/guide/toc.yml
Close: https://github.com/micronaut-projects/micronaut-security/pull/451
=> doc: Clafiy JWT Signature verification/generation

src/main/docs/guide/oauth/flows/authorization-code/openid-authorization-code/openid-auth-parameters/nonce.adoc, src/main/docs/guide/oauth/flows/authorization-code/state.adoc, src/main/docs/guide/oauth/installation.adoc, src/main/docs/guide/oauth/openid.adoc
Close: https://github.com/micronaut-projects/micronaut-security/issues/486
=> doc: maven group is io.micronaut.security

security-ldap/src/main/java/io/micronaut/configuration/security/ldap/context/AttributesConvertibleValues.java, security-ldap/src/test/groovy/io/micronaut/configuration/security/ldap/context/AttributesConvertibleValuesSpec.groovy
https://github.com/micronaut-projects/micronaut-security/issues/479
=> fix: AttributesConvertibleValues protect NPE

security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/DefaultJwtAuthenticationFactory.java, security-jwt/src/test/groovy/io/micronaut/security/token/jwt/validator/DefaultJwtAuthenticationFactorySpec.groovy
Close: https://github.com/micronaut-projects/micronaut-security/pull/498
Close: https://github.com/micronaut-projects/micronaut-security/issues/495
=> refactor: no need to create a userdetails

security-oauth2/src/main/java/io/micronaut/security/oauth2/client/clientcredentials/CacheableProcessor.java
see: https://github.com/micronaut-projects/micronaut-security/issues/500
=> fix: don't use list but concurrent linked queue

src/main/docs/guide/oauth/flows/clientcredentials/clientecredentialshttpclient.adoc
remove trailing comma,
remove unnecessary quotations
=> docs: security->oauth2->client_cerdentials: fix typo in secret, optimize params

security/src/main/java/io/micronaut/security/filters/SecurityFilter.java
Close: https://github.com/micronaut-projects/micronaut-security/issues/574
=> refactor: instantiate map only if log level debug

security-ldap/src/main/resources/META-INF/native-image/io.micronaut.security/ldap/reflect-config.json
Close: https://github.com/micronaut-projects/micronaut-security/issues/591
Close: https://github.com/micronaut-projects/micronaut-security/issues/512
=> build: graalvm reflect-config.json for gralvm

security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/authorization/response/AuthorizationErrorCode.java, security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/authorization/response/AuthorizationErrorCodeSpec.groovy
Close: https://github.com/micronaut-projects/micronaut-security/issues/605
=> feat: add unauthorized_scope_error and user_cancelled_authorize error codes

security-oauth2/src/main/java/io/micronaut/security/oauth2/url/DefaultOauthRouteUrlBuilder.java, security-oauth2/src/test/groovy/io/micronaut/security/oauth2/url/OauthRouteUrlBuilderSpec.groovy
close: https://github.com/micronaut-projects/micronaut-security/issues/370
close: https://github.com/micronaut-projects/micronaut-security/pull/643
=> fix: Support absolute configs for oauth callback and login

security-oauth2/src/main/java/io/micronaut/security/oauth2/client/DefaultOauthClient.java
delete deprecated method DefaultOauthClient::getTokenEndpoint
=> BREAKING CHANGE: delete getTokenEndpoint

security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/OauthUserDetailsMapper.java, security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/authorization/request/OauthAuthorizationRedirectSpec.groovy, security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/authorization/request/OpenIdAuthorizationRedirectOauthDisabledSpec.groovy, security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/authorization/request/OpenIdAuthorizationRedirectSpec.groovy, test-suite-groovy/src/test/groovy/io/micronaut/security/oauth2/docs/endpoint/CsrfFilterSpec.groovy, test-suite-groovy/src/test/groovy/io/micronaut/security/oauth2/docs/github/GithubUserDetailsMapper.groovy, test-suite-kotlin/src/test/kotlin/io/micronaut/security/oauth2/docs/github/GithubUserDetailsMapper.kt, test-suite/src/test/java/io/micronaut/security/oauth2/docs/github/GithubUserDetailsMapper.java
delete deprecated method OauthUserDetailsMapper::createUserDetails(TokenResponse)
=> BREAKING CHANGE: del createUserDetails(TokenResponse)

security-session/src/main/java/io/micronaut/security/session/SessionLoginHandler.java
SessionLoginHandler(SecuritySessionConfiguration,SessionStore<Session>,TokenConfiguration)
=> BREAKING CHANGE: SessionLoginHandler constructor

security/src/main/java/io/micronaut/security/utils/DefaultSecurityService.java, security/src/test/groovy/io/micronaut/security/authorization/SecuredRolesCaseSensitiveSpec.groovy
Delete deprecated constructor DefaultSecurityService(TokenConfiguration)
=> BREAKING CHANGE: constr DefaultSecurityService

security/src/main/java/io/micronaut/security/authentication/BasicAuthAuthenticationFetcher.java, security/src/test/groovy/io/micronaut/security/authentication/BasicAuthAuthenticationFetcherSpec.groovy
del BasicAuthAuthenticationFetcher::parseCredentials
=> BREAKING CHANGE: del parseCredentials

security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/AudienceJwtClaimsValidator.java, security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/ExpirationJwtClaimsValidator.java, security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/IssuerJwtClaimsValidator.java, security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/JwtClaimsValidator.java, security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/NotBeforeJwtClaimsValidator.java, security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/SubjectNotNullJwtClaimsValidator.java, security-jwt/src/test/groovy/io/micronaut/security/token/jwt/validator/JwtClaimsValidatorRequestNotPassedByDefaultSpec.groovy, security-jwt/src/test/groovy/io/micronaut/security/token/jwt/validator/JwtClaimsValidatorRequestPassedSpec.groovy, security-oauth2/src/main/java/io/micronaut/security/oauth2/client/IdTokenClaimsValidator.java, security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/validation/DefaultOpenIdTokenResponseValidator.java
Delete deprecated method JwtClaimsValidator:validate(JwtClaims)
=> BREAKING CHANGE: del JwtClaimsValidator:validate

security-jwt/src/main/java/io/micronaut/security/token/jwt/generator/claims/JWTClaimsSetGenerator.java, security-jwt/src/test/groovy/io/micronaut/security/token/jwt/generator/claims/JWTClaimsSetGeneratorSpec.groovy
delete constructor JWTClaimsSetGenerator(TokenConfiguration,JwtIdGenerator, ClaimsAudienceProvider)
=> BREAKING CHANGE: del JWTClaimsSetGenerator constru

security/src/main/java/io/micronaut/security/token/event/RefreshTokenGeneratedEvent.java
delete deprecated constructor RefreshTokenGeneratedEvent(Object)
=> BREAKING CHANGE: RefreshTokenGeneratedEvent constr

security-jwt/src/main/java/io/micronaut/security/token/jwt/cookie/CookieLoginHandler.java, security-jwt/src/main/java/io/micronaut/security/token/jwt/cookie/JwtCookieLoginHandler.java, security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/IdTokenLoginHandler.java
It's an additional PR to that one: https://github.com/micronaut-projects/micronaut-security/pull/633
=> Added javadoc for PR #633

security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/DefaultOpenIdUserDetailsMapper.java
delete deprecated DefaultOpenIdUserDetailsMapper constructor
=> BREAKING CHANGE: DefaultOpenIdUserDetailsMapper

security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/JwtValidator.java, security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/validation/DefaultOpenIdTokenResponseValidator.java
Delete methods:
- JwtValidator::validate(String)
- JwtValidator::validate(JWT)
=> BREAKING CHANGE: deprecated JwtValidator::validate

security/src/test/groovy/io/micronaut/security/endpoints/introspection/IntrospectionResponseSpec.groovy
Issue https://github.com/micronaut-projects/micronaut-core/issues/4179 has been solved since 2.5.6
=> test: remove pending feature

security/src/main/java/io/micronaut/security/authentication/AuthenticationUserDetailsAdapter.java
=> fix: AuthenticationUserDetailsAdapter serialisable in native image

security/src/test/groovy/io/micronaut/security/authentication/AuthenticationUserDetailsAdapterSpec.groovy
Missing test for https://github.com/micronaut-projects/micronaut-security/pull/703
=> test: AuthenticationUserDetailsAdapter @Introspected

src/main/docs/guide/oauth/flows/clientcredentials/clientecredentialshttpclient.adoc
Fixes the poorly formulated sentence from the docs (#717).
=> Fix: Typo in doc (#717)

src/main/docs/guide/oauth/flows/clientcredentials.adoc, src/main/docs/guide/oauth/flows/clientcredentials/clientecredentialshttpclient.adoc
Just a couple of small typos I noticed in the docs.
=> Small typo in docs

security-jwt/src/main/java/io/micronaut/security/token/jwt/cookie/JwtCookieConfigurationProperties.java, security-jwt/src/main/java/io/micronaut/security/token/jwt/cookie/RefreshTokenCookieConfigurationProperties.java, security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/authorization/state/persistence/cookie/CookieStatePersistenceConfiguration.java, security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/nonce/persistence/cookie/CookieNoncePersistenceConfiguration.java, src/main/docs/guide/breaks.adoc, test-suite-utils/src/main/groovy/io/micronaut/security/testutils/ConfigurationFixture.groovy
The new default value is request.isSecure()
=> Change cookie secure configuration to no longer have a default

src/main/docs/guide/securityRule.adoc
see https://github.com/micronaut-projects/micronaut-security/issues/689
=> doc: since 2.5. security rule cannot access Body

security-jwt/src/main/java/io/micronaut/security/token/jwt/cookie/JwtCookieConfigurationProperties.java, security-jwt/src/main/java/io/micronaut/security/token/jwt/cookie/RefreshTokenCookieConfigurationProperties.java, security-jwt/src/test/groovy/io/micronaut/security/token/jwt/cookie/JwtCookieSameSiteCaseSensitiveSpec.groovy
=> doc: same-site is case sensitive

security-oauth2/src/main/java/io/micronaut/security/oauth2/client/DefaultOpenIdProviderMetadata.java, security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/authorization/state/DefaultState.java, security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/OpenIdTokenResponse.java, security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/TokenResponse.java
=> Enable native build of OpenID Connect 

security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/endsession/request/AuthorizationServer.java, security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/endsession/request/EndSessionEndpointResolver.java, security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/endsession/request/KeycloakEndSessionEndpoint.java, security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/endsession/request/AuthorizationServerSpec.groovy, security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/endsession/request/KeycloakEndSessionEndpointSpec.groovy, security-oauth2/src/test/groovy/io/micronaut/security/oauth2/keycloak/KeycloakEndSessionEndpoint.groovy, test-suite-utils/src/main/groovy/io/micronaut/security/testutils/Keycloak.groovy
=> Support Keycloak in OpenID Connect end session endpoint

security/src/main/java/io/micronaut/security/rules/IpPatternsRule.java
Close: https://github.com/micronaut-projects/micronaut-security/issues/878
=> fix: Logger name should be IpPatternsRule

src/main/docs/guide/authenticationStrategies/ldap/configuration.adoc
Close: https://github.com/micronaut-projects/micronaut-security/issues/880
=> doc: fix ldap configuration reference unresolved directive

gradle.properties, test-suite-utils/build.gradle
- setup project version to 3.3.0-SNAPSHOT
-  set up micronaut to 3.2.3
- set github core to 3.3.x
=> ci: project to 3.3.0, mn to 3.2.3, branch 3.3.x

security-jwt/src/main/java/io/micronaut/security/token/jwt/cookie/CookieLoginHandler.java, security-jwt/src/main/java/io/micronaut/security/token/jwt/cookie/JwtCookieClearerLogoutHandler.java, security-jwt/src/test/groovy/io/micronaut/security/token/jwt/cookie/JwtCookieAuthenticationNoRedirectSpec.groovy, security-jwt/src/test/groovy/io/micronaut/security/token/jwt/cookie/JwtCookieClearerLogoutHandlerSpec.groovy, security-session/src/main/java/io/micronaut/security/session/SessionLoginHandler.java, security-session/src/main/java/io/micronaut/security/session/SessionLogoutHandler.java, security-session/src/test/groovy/io/micronaut/docs/security/session/SessionAuthenticationNoRedirectSpec.groovy, security/src/main/java/io/micronaut/security/authentication/DefaultAuthorizationExceptionHandler.java, security/src/main/java/io/micronaut/security/config/RedirectConfiguration.java, security/src/main/java/io/micronaut/security/config/RedirectConfigurationProperties.java, src/main/docs/guide/authenticationStrategies/session.adoc, src/main/docs/guide/securityConfiguration/noRedirection.adoc, src/main/docs/guide/toc.yml
Close: https://github.com/micronaut-projects/micronaut-security/issues/844
=> feat: redirect configuration toggeable

security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/token/response/validation/AuthorizedPartyClaimValidatorSpec.groovy
see: https://github.com/micronaut-projects/micronaut-security/pull/899
=> test: azp validator

.github/workflows/graalvm.yml, .github/workflows/gradle.yml
This handles retries better in JUnit tests and
doesn't flag flakiness as a failure
https://github.com/mikepenz/action-junit-report/releases/tag/v2.9.0
=> ci: update to junit-report-action 2.9.0

security-jwt/src/main/java/io/micronaut/security/token/jwt/cookie/JwtCookieConfigurationProperties.java
add closing brackets for default value for HttpOnly and CookiePath attributes
=> doc: Javadoc in JwtCookieConfigurationProperties.java

src/main/docs/guide/authenticationStrategies/x509.adoc
merge after https://github.com/micronaut-projects/micronaut-guides/pull/601 is merged/published
=> add link to the X.509 guide

settings.gradle
=> build. change root project name

security-jwt/src/main/java/io/micronaut/security/token/jwt/render/AccessRefreshToken.java
The pull request includes only a minor javadoc fix in the `AccessRefreshToken` class.
=> Minor javadoc fix

security/src/main/java/io/micronaut/security/config/SecurityConfigurationProperties.java
Close: https://github.com/micronaut-projects/micronaut-security/issues/1006
=> doc: reject not found configuration reference

security/src/main/java/io/micronaut/security/config/SecurityConfigurationProperties.java
see: Close: https://github.com/micronaut-projects/micronaut-security/issues/1006
=> javadoc: use @value

security/src/main/java/io/micronaut/security/config/SecurityConfigurationProperties.java
Add missing AuthenticationMode in description
=> javadoc: add itoken to javadoc

security-jwt/src/test/groovy/io/micronaut/docs/websockets/HomePageSpec.groovy, security-jwt/src/test/groovy/io/micronaut/security/token/jwt/cookie/JwtCookieAuthenticationSpec.groovy, security-jwt/src/test/groovy/io/micronaut/security/token/jwt/cookie/JwtCookiePriorLoginSpec.groovy, security-jwt/src/test/groovy/io/micronaut/security/token/jwt/cookie/JwtCookieRefreshSpec.groovy, security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/endsession/request/KeycloakEndSessionEndpointSpec.groovy
./gradlew -Dtestcontainers=false test
=> test: ignore if testcontainers system property is set to false

gradle.properties
- Micronaut Test to 3.5.0
- `githubCoreBranch` to 3.7.x
=> build: Micronaut Framework to 3.6.0

security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/request/password/OpenIdPasswordAuthenticationProvider.java, security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/request/password/PasswordGrantCondition.java, security-oauth2/src/test/groovy/io/micronaut/security/oauth2/client/condition/PasswordGrantConditionSpec.groovy, settings.gradle
Close: https://github.com/micronaut-projects/micronaut-security/pull/1086
Close: https://github.com/micronaut-projects/micronaut-security/pull/1072
Close: https://github.com/micronaut-projects/micronaut-security/issues/1071
=> fix: Issue password grant

buildSrc/build.gradle, buildSrc/src/main/groovy/io.micronaut.build.internal.security-base.gradle, buildSrc/src/main/groovy/io.micronaut.build.internal.security-module.gradle, buildSrc/src/main/groovy/io.micronaut.build.internal.security-tests.gradle, gradle.properties, gradle/libs.versions.toml, security-annotations/build.gradle, security-jwt/build.gradle, security-ldap/build.gradle, security-oauth2/build.gradle, security-session/build.gradle, security/build.gradle, test-suite-groovy/build.gradle, test-suite-kotlin/build.gradle, test-suite-serde/build.gradle, test-suite-tomcat-groovy/build.gradle, test-suite-tomcat/build.gradle, test-suite-utils-security/build.gradle, test-suite-utils/build.gradle, test-suite/build.gradle
=> Modernize the build, aligning it more closely to best practices defined by project-template

security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/authorization/response/AuthorizationErrorResponseExceptionHandler.java, security/src/main/java/io/micronaut/security/authentication/AuthenticationExceptionHandler.java, security/src/main/java/io/micronaut/security/authentication/DefaultAuthorizationExceptionHandler.java
See https://github.com/micronaut-projects/micronaut-security/pull/921
=> Deprecate constructors to be removed in the next major version

config/accepted-api-changes.json, security-jwt/src/main/java/io/micronaut/security/token/jwt/cookie/CookieLoginHandler.java, security-jwt/src/main/java/io/micronaut/security/token/jwt/cookie/JwtCookieClearerLogoutHandler.java, security-jwt/src/main/java/io/micronaut/security/token/jwt/cookie/JwtCookieLoginHandler.java, security-jwt/src/main/java/io/micronaut/security/token/jwt/generator/DefaultAccessRefreshTokenGenerator.java, security-jwt/src/test/groovy/io/micronaut/docs/rejection/MyRejectionHandler.java, security-jwt/src/test/groovy/io/micronaut/security/token/jwt/bearer/AccessRefreshTokenLoginHandlerSpec.groovy, security-jwt/src/test/groovy/io/micronaut/security/token/jwt/cookie/JwtCookieClearerLogoutHandlerSpec.groovy, security-oauth2/src/main/java/io/micronaut/security/oauth2/configuration/OauthClientConfiguration.java, security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/authorization/response/AuthorizationErrorResponseExceptionHandler.java, security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/IdTokenLoginHandler.java, security-oauth2/src/main/java/io/micronaut/security/oauth2/routes/DefaultOauthController.java, security-session/src/main/java/io/micronaut/security/session/SessionLoginHandler.java, security-session/src/main/java/io/micronaut/security/session/SessionLogoutHandler.java, security/src/main/java/io/micronaut/security/authentication/AuthenticationExceptionHandler.java, security/src/main/java/io/micronaut/security/authentication/DefaultAuthorizationExceptionHandler.java, security/src/main/java/io/micronaut/security/endpoints/LoginController.java, security/src/main/java/io/micronaut/security/endpoints/LogoutController.java, security/src/main/java/io/micronaut/security/errors/OauthErrorResponseExceptionHandler.java, security/src/main/java/io/micronaut/security/rules/IpPatternsRule.java, security/src/main/java/io/micronaut/security/rules/SecuredAnnotationRule.java, security/src/main/java/io/micronaut/security/token/TokenAuthenticationFetcher.java
- It Uses ErrorProcessorAPI in ErorHandlers
- It Specifies event type for ApplicationEventPublisher
=> BREAKING: remove @Deprecated

security-oauth2/src/test/groovy/io/micronaut/security/oauth2/configuration/CorsConfigurationSpec.groovy, security/src/main/java/io/micronaut/security/config/DefaultInterceptUrlPatternModifier.java, security/src/main/java/io/micronaut/security/config/InterceptUrlMapConverter.java, security/src/main/java/io/micronaut/security/config/InterceptUrlPatternModifier.java, security/src/main/java/io/micronaut/security/config/SecurityConfigurationProperties.java, security/src/main/java/io/micronaut/security/rules/ConfigurationInterceptUrlMapRule.java, security/src/test/groovy/io/micronaut/security/config/InterceptUrlMapConverterContextPathByDefaultSpec.groovy, test-suite-tomcat-groovy/build.gradle, test-suite-tomcat/build.gradle
=> fix: decouple converter from config

.github/workflows/graalvm.yml, security-jwt/src/test/groovy/io/micronaut/security/token/jwt/signature/jwks/JwksCacheSpec.groovy
JwksCacheSpec has been flaky.  This PR removes the flakiness and it rewrites the test to be more succinct, moving repetition into methods
=> test: Reduce JwksCacheSpec flakiness

.github/workflows/graalvm.yml, security-oauth2/build.gradle, security-oauth2/src/main/java/io/micronaut/security/oauth2/client/DefaultOpenIdProviderMetadataFetcher.java, security-oauth2/src/main/java/io/micronaut/security/oauth2/client/OpenIdClientFactory.java, security-oauth2/src/test/groovy/io/micronaut/security/oauth2/client/JwksUriSignatureSpec.groovy, security-oauth2/src/test/groovy/io/micronaut/security/oauth2/client/OpenIdClientFactorySpec.groovy
OpenID connect metadata fetching should not be done in netty event loop thread.
See: https://github.com/micronaut-projects/micronaut-security/issues/604
=> Fetch OpenID Connect metadata with @Contex and @parallel  don't block the netty event loop

security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/ec/ECSignatureConfiguration.java, security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/ec/ECSignatureGenerator.java, security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/ec/ECSignatureGeneratorConfiguration.java, security-jwt/src/test/groovy/io/micronaut/security/token/jwt/signature/ec/ECSignatureConfigurationSpec.groovy, security-jwt/src/test/groovy/io/micronaut/security/token/jwt/signature/ec/JwkParser.java, security-jwt/src/test/groovy/io/micronaut/security/token/jwt/signature/ec/TestECSignatureGeneratorConfiguration.java, security-jwt/src/test/groovy/io/micronaut/security/token/jwt/signature/ec/TestECSignatureGeneratorConfigurationWithKid.java
=> add kid to jwt header for EC signature

security-ldap/src/main/java/io/micronaut/security/ldap/LdapEnabledCondition.java, security-oauth2/src/main/java/io/micronaut/security/oauth2/client/clientcredentials/ClientCredentialsEnabled.java, security-oauth2/src/main/java/io/micronaut/security/oauth2/client/clientcredentials/propagation/ClientCredentialsHeaderPropagatorEnabled.java, security-oauth2/src/main/java/io/micronaut/security/oauth2/client/condition/AbstractCondition.java, security-oauth2/src/main/java/io/micronaut/security/oauth2/client/condition/OpenIdClientCondition.java, security/src/main/java/io/micronaut/security/utils/NamedUtils.java, security/src/main/java/io/micronaut/security/utils/QualifierUtils.java
=> refactor: extract NamedUtils

gradle/libs.versions.toml, security-oauth2/build.gradle, security-session/build.gradle.kts, settings.gradle, test-suite-tomcat-groovy/build.gradle, test-suite-tomcat/build.gradle
=> Update build to use micronaut-servlet and micronaut-session

security-oauth2/src/main/java/io/micronaut/security/oauth2/client/DefaultOpenIdClient.java, security-oauth2/src/test/groovy/io/micronaut/security/oauth2/client/DefaultOpenIdClientSpec.groovy
=> fix: multiple possible candidates for DefaultOpenIdProviderMetadata

.github/workflows/graalvm.yml, .github/workflows/gradle.yml, .github/workflows/release.yml, settings.gradle
=> build: update to 5.4.0 and sync workflows

security/src/main/java/io/micronaut/security/endpoints/introspection/IntrospectionResponse.java, test-suite-graal/src/test/java/io/micronaut/security/graal/IntrospectionResponseTest.java
=> Fix reflective access introspection response

.github/workflows/graalvm.yml, security-jwt/src/test/groovy/io/micronaut/docs/base64/JwtBase64Spec.groovy, security-jwt/src/test/groovy/io/micronaut/docs/signandencrypt/SignSecretEncryptRSASpec.groovy, security/src/test/groovy/io/micronaut/docs/security/securityRule/builtinendpoints/BuiltInEndpointsSpec.groovy, security/src/test/groovy/io/micronaut/docs/security/securityRule/intercepturlmap/InterceptUrlMapSpec.groovy, src/main/docs/guide/authenticationStrategies/jwt/jwtEncryption/jwtGeneratorEncryption.adoc, src/main/docs/guide/authenticationStrategies/jwt/jwtGenerator/jwtGeneratorSecret.adoc, src/main/docs/guide/authenticationStrategies/jwt/jwtValidation/jwks.adoc, src/main/docs/guide/authenticationStrategies/session.adoc, src/main/docs/guide/authenticationStrategies/x509.adoc, src/main/docs/guide/endpoints/refresh.adoc, src/main/docs/guide/introduction.adoc, src/main/docs/guide/oauth.adoc, src/main/docs/guide/oauth/flows/authorization-code/oauth2-authorization-code/oauth2-configuration.adoc, src/main/docs/guide/oauth/flows/authorization-code/openid-authorization-code/openid-auth-parameters/nonce.adoc, src/main/docs/guide/oauth/flows/authorization-code/openid-authorization-code/openid-configuration.adoc, src/main/docs/guide/oauth/flows/authorization-code/state.adoc, src/main/docs/guide/oauth/flows/clientcredentials.adoc, src/main/docs/guide/oauth/flows/clientcredentials/clientecredentialshttpclient.adoc, src/main/docs/guide/oauth/flows/password.adoc, src/main/docs/guide/securityRule/builtInEndpointsAccess.adoc, src/main/docs/guide/securityRule/interceptUrlMap.adoc, src/main/docs/guide/securityRule/ipPattern.adoc, src/main/docs/guide/tokenPropagation.adoc
=> Issue 1203 - update docs to use configuration snippets

security-oauth2/src/test/groovy/io/micronaut/security/oauth2/client/clientcredentials/ClientCredentialsConcurrentSpec.groovy
The reason it previously failed in CI seems to be related to: https://stackoverflow.com/a/66861540/2138
=> test: run CompleteableFuture test on ci

security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/jwks/JWKSetJwksSignature.java, security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/jwks/JwksSignature.java, security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/jwks/JwksSignatureConfiguration.java, security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/jwks/JwksSignatureUtils.java, security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/jwks/StaticJwksSignature.java, security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/jwks/StaticJwksSignatureConfiguration.java, security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/jwks/StaticJwksSignatureConfigurationProperties.java, security-jwt/src/test/groovy/io/micronaut/docs/jwks/StaticJwksSignatureSpec.groovy, security-jwt/src/test/groovy/io/micronaut/security/token/jwt/signature/jwks/JwsSignatureSpec.groovy, security-jwt/src/test/groovy/io/micronaut/security/token/jwt/signature/jwks/StaticJwksSignatureConfigurationPropertiesSpec.groovy, security-jwt/src/test/groovy/io/micronaut/security/token/jwt/signature/jwks/StaticJwksSignatureConfigurationSpec.groovy, security-jwt/src/test/resources/jwks/certs.json, src/main/docs/guide/authenticationStrategies/jwt/jwtValidation/jwks/staticJwks.adoc, src/main/docs/guide/toc.yml
This PR adds the ability to serve a JSON JWKS from anywhere on disk or in the classpath. 
Fixes #1109
=> static JWKS

src/main/docs/guide/securityRule.adoc, src/main/docs/guide/securityRule/interceptUrlMap.adoc, src/main/docs/guide/securityRule/secured.adoc
Here's the docs addition described in #1305. I tried executing `./gradlew publishGuide` but i get a "build failed". I guess this is due to a local misconfiguration.
=> doc: better security rules documentation (#1305)

security/src/main/java/io/micronaut/security/filters/SecurityFilter.java
=> fix: prevent NPE in SecurityFilter

security-oauth2/src/main/java/io/micronaut/security/oauth2/client/clientcredentials/AbstractClientCredentialsClient.java, security-oauth2/src/test/groovy/io/micronaut/security/oauth2/client/clientcredentials/ClientCredentialsSpec.groovy
Closes https://github.com/micronaut-projects/micronaut-security/issues/1376
Closes https://github.com/micronaut-projects/micronaut-security/issues/991
Please let me know if you need me to target another branch, or if you have any concerns with the approach/tests. We are very motivated to get this merged as soon as we can. Currently, we're patching this class in manually on our service.
=> Bug Fix: No longer cache and replay errors in AbstractClientCredentialsClient

security-aot/build.gradle.kts
- Updates micronau-aot to the latest version
=> update AOT to latest version

.github/workflows/release.yml
see: https://github.com/micronaut-projects/micronaut-project-template/issues/389
try in security the change to project template https://github.com/micronaut-projects/micronaut-project-template/pull/390
=> run post release after github-release

security/src/main/java/io/micronaut/security/token/reader/TokenResolver.java, security/src/test/groovy/io/micronaut/security/token/reader/TokenResolverSpec.groovy
I should have added it here: https://github.com/micronaut-projects/micronaut-security/pull/1498
=> add default implementation method TokenResolver::resolveTokens

gradle/libs.versions.toml, settings.gradle, src/main/docs/guide/retrievingAuthenticatedUser/securityService.adoc, test-suite-security-service/build.gradle.kts, test-suite-security-service/src/test/java/io/micronaut/security/tests/TestSuiteSecurityServiceTest.java, test-suite-security-service/src/test/java/io/micronaut/security/tests/controllers/FooController.java, test-suite-security-service/src/test/java/io/micronaut/security/tests/entity/ResourceEntity.java, test-suite-security-service/src/test/java/io/micronaut/security/tests/repository/ResourceReactorCrudRepository.java, test-suite-security-service/src/test/java/io/micronaut/security/tests/repository/ResourceReactorRepositoryAdapter.java, test-suite-security-service/src/test/java/io/micronaut/security/tests/repository/ResourceRepository.java, test-suite-security-service/src/test/java/io/micronaut/security/tests/security/SherlockTokenValidator.java, test-suite-security-service/src/test/resources/logback.xml
=> doc: reactor context propagation for SecurityService

gradle/libs.versions.toml, security-jwt/build.gradle.kts, security-ldap/build.gradle.kts, security-oauth2/build.gradle.kts, security/build.gradle.kts, settings.gradle, test-suite-hibernate-validator/build.gradle.kts, test-suite-hibernate-validator/src/test/java/io/micronaut/security/jacksondatabind/beanintrospectionfalse/LoginControllerValidationTest.java, test-suite-hibernate-validator/src/test/resources/logback.xml
Verify it works with [micronaut-hibernate-validator](https://micronaut-projects.github.io/micronaut-hibernate-validator/latest/guide/)
=> fix: don’t expose validation

src/main/docs/guide/breaks.adoc
Close: https://github.com/micronaut-projects/micronaut-security/issues/1545
=> doc: breaking change AuthenticationProvider<HttpRequest<?>>

src/main/docs/guide/breaks.adoc
see: https://github.com/micronaut-projects/micronaut-security/issues/1545
=> doc: removal of SecurityRule#check RouteMatch arg

gradle.properties, security-oauth2/src/main/java/io/micronaut/security/oauth2/routes/DefaultOauthController.java, security/src/main/java/io/micronaut/security/endpoints/LoginController.java, security/src/main/java/io/micronaut/security/endpoints/LogoutController.java, security/src/main/java/io/micronaut/security/event/LoginFailedEvent.java, security/src/main/java/io/micronaut/security/event/LoginSuccessfulEvent.java, security/src/main/java/io/micronaut/security/event/LogoutEvent.java, security/src/main/java/io/micronaut/security/event/SecurityEvent.java, security/src/main/java/io/micronaut/security/event/TokenValidatedEvent.java, security/src/main/java/io/micronaut/security/token/TokenAuthenticationFetcher.java, security/src/main/java/io/micronaut/security/token/cookie/TokenCookieClearerLogoutHandler.java, security/src/test/groovy/io/micronaut/security/events/EventListenerSpec.groovy, security/src/test/groovy/io/micronaut/security/token/TokenAuthenticationFetcherSpec.groovy
Closes #1622 
I created a 4.7.x branch, and this also bumps the version to 4.7.0-SNAPSHOT
=> Add locale and host to security events

security-oauth2/src/main/java/io/micronaut/security/oauth2/routes/DefaultOauthController.java
Extract two private methods for clarity.
=> refactor: extract methods
